# Generated by Django 4.1.3 on 2022-12-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_alter_tarea_estado_alter_tarea_fecha_entrega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(max_length=7),
        ),
    ]
